/**
 * YouTube Tools Type Definitions
 */

// ============================================================================
// Video Types
// ============================================================================

export interface YouTubeVideo {
    /** Video ID (e.g., 'dQw4w9WgXcQ') */
    videoId: string;

    /** Video title */
    title: string;

    /** Video description (may be truncated) */
    description?: string;

    /** Published date in ISO 8601 format */
    publishedAt: string;

    /** Video duration in 'HH:MM:SS' or 'MM:SS' format */
    duration?: string;

    /** Duration in seconds */
    durationSeconds?: number;

    /** View count */
    viewCount?: number;

    /** Like count */
    likeCount?: number;

    /** Comment count */
    commentCount?: number;

    /** Thumbnail URLs */
    thumbnails?: YouTubeThumbnails;

    /** Channel ID */
    channelId?: string;

    /** Channel title/name */
    channelTitle?: string;

    /** Video URL */
    url: string;
}

export interface YouTubeThumbnails {
    default?: string;
    medium?: string;
    high?: string;
    standard?: string;
    maxres?: string;
}

// ============================================================================
// Channel Types
// ============================================================================

export interface YouTubeChannel {
    /** Channel ID */
    channelId: string;

    /** Channel name */
    title: string;

    /** Channel description */
    description?: string;

    /** Custom URL or handle (@username) */
    customUrl?: string;

    /** Subscriber count (may be hidden) */
    subscriberCount?: number;

    /** Total video count */
    videoCount?: number;

    /** Total view count */
    viewCount?: number;

    /** Channel thumbnails/avatars */
    thumbnails?: YouTubeThumbnails;

    /** Channel banner images */
    banners?: YouTubeThumbnails;

    /** Channel URL */
    url: string;

    /** Channel creation date */
    publishedAt?: string;
}

// ============================================================================
// Transcript Types
// ============================================================================

export interface TranscriptSegment {
    /** Start time in seconds */
    start: number;

    /** Duration in seconds */
    duration: number;

    /** Text content */
    text: string;

    /** End time in seconds (start + duration) */
    end?: number;
}

export interface TranscriptOptions {
    /** Language code (e.g., 'en', 'vi'). Auto-detect if not specified */
    lang?: string;

    /** Output format */
    format?: 'json' | 'text' | 'srt' | 'vtt';
}

export interface TranscriptInfo {
    /** Available language codes */
    availableLanguages: string[];

    /** Whether auto-generated captions are available */
    hasAutoGenerated: boolean;

    /** Whether manual captions are available */
    hasManual: boolean;
}

// ============================================================================
// Options Types
// ============================================================================

export interface GetChannelVideosOptions {
    /** Channel ID, URL, or handle (@username) */
    channel: string;

    /** Maximum number of videos to fetch. Default: all */
    limit?: number;

    /** Sort order */
    sortBy?: 'newest' | 'oldest' | 'popular';

    /** Use RSS feed only (faster but limited to 15 videos) */
    rssOnly?: boolean;
}

export interface GetVideoInfoOptions {
    /** Video ID or URL */
    video: string;
}

export interface SearchOptions {
    /** Search query */
    query: string;

    /** Maximum results */
    limit?: number;

    /** Filter by upload date */
    uploadDate?: 'hour' | 'today' | 'week' | 'month' | 'year';

    /** Filter by duration */
    duration?: 'short' | 'medium' | 'long';

    /** Filter by type */
    type?: 'video' | 'channel' | 'playlist';

    /** Sort by */
    sortBy?: 'relevance' | 'date' | 'viewCount' | 'rating';
}

// ============================================================================
// Error Types
// ============================================================================

export class YouTubeToolsError extends Error {
    constructor(
        message: string,
        public code: string,
        public statusCode?: number,
    ) {
        super(message);
        this.name = 'YouTubeToolsError';
    }
}

export const ErrorCodes = {
    INVALID_INPUT: 'INVALID_INPUT',
    CHANNEL_NOT_FOUND: 'CHANNEL_NOT_FOUND',
    VIDEO_NOT_FOUND: 'VIDEO_NOT_FOUND',
    TRANSCRIPT_NOT_AVAILABLE: 'TRANSCRIPT_NOT_AVAILABLE',
    RATE_LIMITED: 'RATE_LIMITED',
    PARSING_ERROR: 'PARSING_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
} as const;
